# Dockerfile used for Orca scanning 

#alpine:3.23.3
FROM alpine:3.23.5

# Pull latest security patches for base image packages (libssl3/libcrypto3, musl,
# etc.) so scanners see the current v3.23 branch versions rather than whatever
# was baked into the base image tag.
RUN apk update && apk upgrade --no-cache

ARG OS
ARG ARCH

# List of required binaries
# These should be built ahead of time into .go/bin/${OS}_${ARCH}/
COPY .go/bin/${OS}_${ARCH}/forwarder /usr/local/bin/forwarder
COPY .go/bin/${OS}_${ARCH}/subscriber /usr/local/bin/subscriber
COPY .go/bin/${OS}_${ARCH}/metricsconfigurator /usr/local/bin/metricsconfigurator
COPY .go/bin/${OS}_${ARCH}/pollerconfigurator /usr/local/bin/pollerconfigurator

RUN chmod +x /usr/local/bin/forwarder /usr/local/bin/subscriber /usr/local/bin/metricsconfigurator /usr/local/bin/pollerconfigurator

# Optional: provide a default command or entrypoint
ENTRYPOINT ["/bin/sh"]
