version = 0.1
[default.deploy.parameters]
stack_name = "aws-integration-h4o7q6br"
resolve_s3 = true
s3_prefix = "aws-integration-h4o7q6br"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "DestinationUri=\"s3://175914298205-uzmd8qujctz6j3c5s5cecynzg1y7eusw2a-s3alias/ds1TStTSagWIRa13Mlzg/\" DataAccessPointArn=\"arn:aws:s3:us-west-2:723346149663:accesspoint/175914298205\" NameOverride=\"\" ForwarderIAMRoleARN=\"arn:aws:iam::780018755362:role/alex-manual-role\" SourceBucketNames=\"\" SourceObjectKeys=\"*\" SourceTopicArns=\"\" SourceKMSKeyArns=\"\" ContentTypeOverrides=\"\" MaxFileSize=\"\" MemorySize=\"\" Timeout=\"\" DebugEndpoint=\"\" Verbosity=\"\""
image_repositories = []
disable_rollback = true
