---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stream CloudWatch Metrics to S3.'
Metadata:
  AWS::ServerlessRepo::Application:
    Name: observe-metric-stream
    Description: Stream CloudWatch Metrics to S3.
    Author: Observe Inc
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/observeinc/aws-sam-apps
    SemanticVersion: '0.0.1'
    SourceCodeUrl: https://github.com/observeinc/aws-sam-apps

Parameters:
  BucketARN:
    Type: String
    Description: >-
      S3 Bucket ARN to write log records to.
    AllowedPattern: "^arn:.*$"
  Prefix:
    Type: String
    Description: >-
      Optional prefix to write metrics to.
    Default: ''
  FilterURI:
    Type: String
    Description: >-
      A file hosted in S3 containing list of metrics to stream.
    Default: 's3://observeinc/cloudwatchmetrics/filters/recommended.yaml'
    AllowedPattern: "^s3:\/\/.*"
  OutputFormat:
    Type: String
    Description: >-
      The output format for CloudWatch Metrics.
    Default: 'json'
    AllowedValues:
      - json
      - opentelemetry0.7
      - opentelemetry1.0
  NameOverride:
    Type: String
    Description: >-
      Set Firehose Delivery Stream name. In the absence of a value, the stack
      name will be used.
    Default: ''
    MaxLength: 64
  BufferingInterval:
    Type: Number
    Default: 60
    MinValue: 60
    MaxValue: 900
    Description: |
      Buffer incoming data for the specified period of time, in seconds, before
      delivering it to the destination.
  BufferingSize:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 64
    Description: |
      Buffer incoming data to the specified size, in MiBs, before delivering it
      to the destination.

Conditions:
  UseStackName: !Equals
    - !Ref NameOverride
    - ''

Resources:
  DeliveryStreamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: logging
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt LogGroup.Arn
        - PolicyName: s3writer
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Resource:
                  - !Ref BucketARN
                  - !Sub '${BucketARN}/${Prefix}*'
  LogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Join
        - ''
        - - /aws/firehose/
          - !If
            - UseStackName
            - !Ref AWS::StackName
            - !Ref NameOverride
      RetentionInDays: 365
  LogStream:      
    Type: 'AWS::Logs::LogStream'
    Properties: 
      LogStreamName: s3logs
      LogGroupName: !Ref LogGroup
  DeliveryStream:
    Type: 'AWS::KinesisFirehose::DeliveryStream'
    Properties:
      DeliveryStreamName: !If
        - UseStackName
        - !Ref AWS::StackName
        - !Ref NameOverride
      DeliveryStreamType: DirectPut
      S3DestinationConfiguration:
        BucketARN: !Ref BucketARN
        RoleARN: !GetAtt DeliveryStreamRole.Arn
        Prefix: !Sub '${Prefix}AWSLogs/${AWS::AccountId}/cloudwatchmetrics/${AWS::Region}/${OutputFormat}/'
        ErrorOutputPrefix: !Sub '${Prefix}AWSLogs/${AWS::AccountId}/cloudwatchmetrics/${AWS::Region}/errors/'
        BufferingHints:
          IntervalInSeconds: !Ref BufferingInterval
          SizeInMBs: !Ref BufferingSize
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref LogGroup
          LogStreamName: !Ref LogStream
  MetricStreamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - streams.metrics.cloudwatch.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: firehose
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - firehose:DescribeDeliveryStream
                  - firehose:ListDeliveryStreams
                  - firehose:ListTagsForDeliveryStream
                  - firehose:PutRecord
                  - firehose:PutRecordBatch
                Resource: !GetAtt 'DeliveryStream.Arn'
  MetricStream:
    Type: AWS::CloudWatch::MetricStream
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            # Disable false positive when using Fn::Transform
            # https://github.com/aws-cloudformation/cfn-lint/issues/2887
            - E3002
    Properties:
      FirehoseArn: !GetAtt 'DeliveryStream.Arn'
      RoleArn: !GetAtt MetricStreamRole.Arn
      'Fn::Transform':
        Name: "AWS::Include"
        Parameters:
          Location: !Ref FilterURI
      # end of processable content for include
      OutputFormat: !Ref OutputFormat

Outputs:
  Firehose:
    Description: 'Firehose ARN'
    Value: !GetAtt 'DeliveryStream.Arn'
  LogGroupName:
    Description: "Log Group Name"
    Value: !Ref LogGroup
