version = 0.1
[default.deploy.parameters]
stack_name = "chen-test"
resolve_s3 = true
s3_prefix = "chen-test"
region = "ca-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "DestinationUri=\"s3://175914298205-uzmd8qujctz6j3c5s5cecynzg1y7eusw2a-s3alias/ds1fT6xRZsCSraMy1cCL/\" DataAccessPointArn=\"arn:aws:s3:us-west-2:723346149663:accesspoint/175914298205\" ConfigDeliveryBucketName=\"\" IncludeResourceTypes=\"*\" ExcludeResourceTypes=\"\" LogGroupNamePatterns=\"*\" LogGroupNamePrefixes=\"\" ExcludeLogGroupNamePatterns=\"\" MetricStreamFilterUri=\"s3://observeinc/cloudwatchmetrics/filters/recommended.yaml\" ObserveAccountID=\"175914298205\" ObserveDomainName=\"observe-eng.com\" UpdateTimestamp=\"1752189506\" DatasourceID=\"42178470\" MetricsPollerAllowedActions=\"cloudwatch:GetMetricData,cloudwatch:ListMetrics,tag:GetResources\" ObserveAwsAccountId=\"\" DatastreamIds=\"\" SourceBucketNames=\"\" ContentTypeOverrides=\"\" NameOverride=\"\" DebugEndpoint=\"\""
image_repositories = []
