name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        run: |
          make go-lint-all
