name: Run Validate

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r dev-requirements.txt
      - run: make sam-validate-all
