#!/bin/bash
# Write file to source bucket, verify it is copied over to destination bucket
set -euo pipefail

DIE() { echo "$*" 1>&2; exit 1; }

[[ ! -z "${SOURCE}" ]] || DIE "source not set"
[[ ! -z "${DESTINATION}" ]] || DIE "destination not set"

cleanup() {
    rm -f "$TMPFILE"
}

trap cleanup EXIT

TMPFILE=$(mktemp)
TMPNAME=$(basename ${TMPFILE})

echo "{\"hello\": \"world\"}" > "$TMPFILE"

# we include source bucket name in key to help debug where file in destination bucket came from
KEY=${SOURCE}/${TMPFILE}

aws s3 cp ${TMPFILE} s3://${SOURCE}/${KEY} --content-type application/json 1>&2 || DIE "failed to copy file to source"

sleep ${INIT_DELAY:-0}
ORIGINAL=$(aws s3api head-object --bucket ${SOURCE} --key ${KEY} | jq 'del(.LastModified)' || DIE "failed to read file from source")
sleep ${COPY_DELAY:-0}
COPY=$(aws s3api head-object --bucket ${DESTINATION} --key ${KEY} | jq 'del(.LastModified)' || DIE "failed to read file from destination")

[ "$ORIGINAL" = "$COPY" ] || DIE "object differs"
