#!/bin/bash
# Write file to source bucket, verify it is copied over to destination bucket
set -euo pipefail

DIE() { echo "$*" 1>&2; exit 1; }

[[ ! -z "${SOURCE}" ]] || DIE "source not set"
[[ ! -z "${DESTINATION}" ]] || DIE "destination not set"

cleanup() {
    rm -f "$TMPFILE"
}

trap cleanup EXIT

TMPFILE=$(mktemp)
TMPNAME=$(basename ${TMPFILE})

echo "{\"hello\": \"world\"}" > "$TMPFILE"

aws s3 cp ${TMPFILE} s3://${SOURCE} --content-type application/json 1>&2
if [ $? -ne 0 ]; then
    DIE "failed to copy file to source"
fi

ORIGINAL=$(aws s3api head-object --bucket ${SOURCE} --key ${TMPNAME} | jq 'del(.LastModified)')
if [ $? -ne 0 ]; then
    DIE "failed to read file from source"
fi


COPY=$(aws s3api head-object --bucket ${DESTINATION} --key ${TMPNAME} | jq 'del(.LastModified)')
if [ $? -ne 0 ]; then
    DIE "failed to read file from destination"
fi

if [ "$ORIGINAL" = "$COPY" ]; then
    echo "ok"
else
    DIE "object differs"
fi
