#!/bin/bash
set -euo pipefail

DIE() { echo "$*" 1>&2; exit 1; }

[[ ! -z "${SOURCE:-}" ]] || DIE "source not set"

echo "listing ${SOURCE}"
RESULT=$(aws s3 ls ${SOURCE} ${OPTS:-})
[[ ! -z ${RESULT} ]] || DIE "bucket is empty"
